apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: f6koq28eh-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-add90c6b0f.1zgx.p3.openshiftapps.com/rhtap/rhtap-qe-nodejs:bdf046e881aaf09d055cde75a9c08b5e2cf1301c@sha256:a1da9601f95d15f2afeb003aa73d14be7b31a1d49daaf63b57912349c417ea5b
          name: container-image
