apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: f6koq28eh-nodejs
  janus-idp.io/tekton: f6koq28eh-nodejs
  backstage.io/kubernetes-id: f6koq28eh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f6koq28eh-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
