apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: f6koq28eh-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: f6koq28eh-nodejs 
  name: f6koq28eh-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: f6koq28eh-nodejs 
